apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: config
spec:
  selector:
    matchLabels:
      app: config

  template:
    metadata:
      labels:
        app: config

    spec:
      containers:
      - name: ${CONFIG_IMAGE_NAME}
        image: "${ACR_REGISTRY}/${CONFIG_IMAGE_NAME}:${BUILD_NUMBER}"
        env:
          - name: CONFIG_SERVICE_PASSWORD
            value: s3cr3t
          - name: NOTIFICATION_SERVICE_PASSWORD
            value: admin
          - name: STATISTICS_SERVICE_PASSWORD
            value: admin
          - name: ACCOUNT_SERVICE_PASSWORD
            value: admin
          - name: MONGODB_CONNECTION_STRING
            value: ${DB_CONNECTION_STRING}
        ports:
        - containerPort: 8888
      imagePullSecrets:
      - name: "${ACR_SECRET}"

---
kind: Service
apiVersion: v1
metadata:
  name: config
spec:
  selector:
    app: config
  ports:
  - port: 8888
    targetPort: 8888
  